### ISSUE TITLE
HTML5 validity error in potions/content-reordering

### ISSUE THREAD

**Issue by cvrebert** [adamschwartz/magic-of-css#19]
Error: Element `section` (`<section class="b">`) not allowed as child of element `rt` in this context.
Contexts in which element section may be used: Where [flow content](http://www.whatwg.org/specs/web-apps/current-work/#flow-content-1) is expected.
Content model for element `rt`: [Phrasing content.](http://www.whatwg.org/specs/web-apps/current-work/#phrasing-content-1)

(Also, tangentially, just FYI, `<rb>` isn't currently part of HTML5; see also http://www.w3.org/html/wg/tracker/issues/172 )

**Comment by adamschwartz** [comment]
Thanks!
