### ISSUE TITLE
"Site temporarily disabled"

### ISSUE THREAD

**Issue by thelastnode** [adamschwartz/magic-of-css#24]
This page has been temporarily disabled due to a misconfigured custom domain.

http://adamschwartz.co/magic-of-css

**Comment by adamschwartz** [comment]
Thanks @thelastnode. I updated the DNS records but unfortunately still waiting for GH to recognize the changes. I contacted GH support hopefully they will respond soon. Sorry for the inconvenience.

**Comment by thelastnode** [comment]
Seems to be working now :+1:
