### ISSUE TITLE
Static offline files broken because of absolute path

### ISSUE THREAD

**Issue by AndyFang1998** [adamschwartz/magic-of-css#25]
The table of contents links to absolute paths without `index.html` and, as a result, pages are unaccessible when static.

If you want I'd be glad to submit a pull request and fix things.

**Comment by adamschwartz** [comment]
Hey @AndyF, thanks! I appreciate the offer.

However I personally prefer URLs like `http://adamschwartz.co/magic-of-css/chapters/4-color/` over `http://adamschwartz.co/magic-of-css/chapters/4-color/index.html` so I’m not sure if I’d want to make this change to the live website.

If you run a simple [command line server](http://unix.stackexchange.com/questions/32182/simple-command-line-http-server) in your local `magic-of-css/` directory you should be able to view the site without a problem.
