### ISSUE TITLE
when next chapters?

### ISSUE THREAD

**Issue by kosmaa** [adamschwartz/magic-of-css#26]
Sorry for making an issue for this, but I've read the "magic of css" and I love it, for the first time I've read something about css that had sense.. and humour, yet I see that since several months there was no updates, so I was wondering if you will find time to write next chapters, or this project is RIP?..

If not and you are planning adding new chapters soon, I would love to translate the whole text into polish , with your permission, because I think that it is worth to spread the magic of css around the globe ;)

thank you for excellent work so far and good luck with [eager.io](https://eager.io)!

**Comment by adamschwartz** [comment]
Hey @kosmaa, thanks so much for the kind words. It is true that I’ve taken a break from Magic of CSS for a little while, but I do plan to write more chapters, hopefully soon. I can’t give a precise date but I’ll be sure to reach out once I do.

Absolutely! The project is under an MIT-style license, so you’re free to do what you’d like. If you do end up creating a Polish version, please let me know, and I’ll add a link to yours in the README. :smile: 

Thank you! I really appreciate it. Please don’t hesitate to reach out with any more questions. :+1:
