### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by runxel** [adamschwartz/magic-of-css#38]
One thing I learned the hard way: Do not assume the user has its background set to white.
So please set a `background-color`.  

![foo](https://user-images.githubusercontent.com/2277182/61665389-288f4400-acd5-11e9-83a7-cf3817304e6d.png)

**Comment by adamschwartz** [comment]
You’re totally right. Thanks @runxel! https://github.com/adamschwartz/magic-of-css/commit/388c74860d1af0d19e844ac1e3c0436951698d08
