### ISSUE TITLE
3 Pane App

### ISSUE THREAD

**Issue by scottaohara** [adamschwartz/magic-of-css#9]
While playing around with the 3 Pane App, depending on the size of my browser window / if I added too much content to the middle section, the content would get cut off and become unreadable beyond the bottom of the browser window.

I found adding the following css to the .middle selector fixed the issue.

.three-pane-app .bottom .middle {
  height: 100%;
  overflow: auto;
}

however, if the point of the middle column was to not vertically scroll, then never mind :)

Thanks

**Comment by adamschwartz** [comment]
Thanks!
